kafka:
  version: 3.7.0
  replicas: 3
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
zookeeper:
  replicas: 3
entityOperator:
  topicOperator: {}
  userOperator: {}
